### ISSUE TITLE
Upgrading from 1.10.7 -> 1.10.8 breaks on node v8.9.4

### ISSUE THREAD

**Issue by erikt9** [bahmutov/start-server-and-test#232]
Running with node v.8.9.4 and start-server-and-test 1.10.8 I'm getting errors related to `timedPromise.finally is not a function`.  1.10.7 and earlier does not have this issue.

```
{ TypeError: Command failed: ./node_modules/.bin/jest ./.storybook/test_image/storyshotImageCompare.optional.test.js
timedPromise.finally is not a function
    at setExitHandler (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/execa/lib/kill.js:102:29)
    at execa (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/execa/index.js:100:22)
    at runTests (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/src/index.js:99:12)
    at tryCatcher (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/filmfreeway/RubymineProjects/filmfreeway/node_modules/start-server-and-test/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  originalMessage: 'timedPromise.finally is not a function',
  shortMessage: 'Command failed: ./node_modules/.bin/jest ./.storybook/test_image/storyshotImageCompare.optional.test.js\ntimedPromise.finally is not a function',
  command: './node_modules/.bin/jest ./.storybook/test_image/storyshotImageCompare.optional.test.js',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
```

and

```
running tests using command "./node_modules/.bin/jest ./.storybook/test_image/storyshotImageCompare.optional.test.js"
(node:76689) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: timedPromise.finally is not a function
(node:76689) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Chalisi** [comment]
I confirm it was not working on a docker image with node 8, when upgrading to 12, no issue anymore

**Comment by smeijer** [comment]
I've just installed this library for the first time and ran into the same problem.

As upgrading node isn't a solution for me, I've downgraded this library from `1.10.8` to `1.10.7`, and that fixed the problem.

A breaking change in a patch version isn't very nice. I can imagine that some users will run into problems because of this.

**Comment by wormyy** [comment]
Same for me. It was happening only on the CI. Thanks @smeijer for the tip, downgrading helped.

**Comment by bahmutov** [comment]
Yeah this was due to a dependency doing a node major update in a feature release

**Comment by ahmetoz** [comment]
the same issue for us 😞 any solutions for it ?

**Comment by smeijer** [comment]
Downgrade to 1.10.7
